;;; Basic repositories.
(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives '(("elpa"  . "http://tromey.com/elpa/")
			 ("gnu"   . "http://elpa.gnu.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")
			 ("org"   . "https://orgmode.org/elpa/")))
(package-initialize)

;;; Secure the `use-package` macro.
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;;; Load other config files.

;; Files that should be loaded first.
;; (load "~/.emacs.d/secrets.el")
;; (load "~/.emacs.d/config/company.el")

;; All the other files.
;; (mapc (lambda (f) (load f))
      ;; (directory-files "~/.emacs.d/config" t "el$"))

;; Witchmacs-like stuff below.
(load-theme 'Witchmacs t)
(org-babel-load-file (expand-file-name "~/.emacs.d/config.org"))

;;; Autogenerated stuff below.
(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes (quote (Witchmacs)))
 '(package-selected-packages
   (quote
    (abbrev avy which-key spaceline-helm-mode spaceline diminish auto-package-update yasnippet use-package tuareg slime-company paredit markdown-mode magit lua-mode helm haskell-mode go-mode gnuplot evil elfeed company-c-headers auctex))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 )
