;;; Basic repositories.
(require 'package)
(setq package-enable-at-startup nil)
(setq package-archives '(("elpa"  . "http://tromey.com/elpa/")
			 ("gnu"   . "http://elpa.gnu.org/packages/")
			 ("melpa" . "https://melpa.org/packages/")
			 ("org"   . "https://orgmode.org/elpa/")))
(package-initialize)

;;; Secure the `use-package` macro.
(unless (package-installed-p 'use-package)
  (package-refresh-contents)
  (package-install 'use-package))

;;; Load other config files.

;; Files that should be loaded first.
(load "~/.emacs.d/secrets.el")
(load "~/.emacs.d/config/company.el")

;; All the other files.
(mapc (lambda (f) (load f))
      (directory-files "~/.emacs.d/config" t "el$"))

;;; Autogenerated stuff below.

(custom-set-variables
 ;; custom-set-variables was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(custom-enabled-themes nil)
 '(haskell-process-auto-import-loaded-modules t)
 '(haskell-process-log t)
 '(haskell-process-suggest-remove-import-lines t)
 '(haskell-process-type (quote cabal-repl))
 '(haskell-tags-on-save t)
 '(package-selected-packages
   (quote
    (org-drill zerodark-theme yasnippet utop use-package twilight-bright-theme tuareg tao-theme spacemacs-theme spaceline solarized-theme slime-company paredit moe-theme minimal-theme markdown-mode magit lua-mode kaolin-themes ido-vertical-mode helm haskell-mode go-mode gnuplot-mode gnuplot exwm elfeed doom-themes counsel company-irony company-c-headers color-theme-sanityinc-solarized auctex))))
(custom-set-faces
 ;; custom-set-faces was added by Custom.
 ;; If you edit it by hand, you could mess it up, so be careful.
 ;; Your init file should contain only one such instance.
 ;; If there is more than one, they won't work right.
 '(default ((t (:inherit nil :stipple nil :background "white" :foreground "black" :inverse-video nil :box nil :strike-through nil :overline nil :underline nil :slant normal :weight normal :height 110 :width normal :foundry "ADBO" :family "Source Code Pro")))))
