#!/bin/sh

# Back up away the most important directory.
rsync -av --delete "$HOME/documents" "$1"backup

# Back up some other files that for one reason or another are not in
# the most important directory.
mkdir -p "$1"backup/misc
rsync -av --delete "$HOME/.emacs.d/feeds.el" "$1"backup/misc/

notify-send -u normal "Backup" "Backup completed!"
