#!/bin/sh
#
# Somehow better than `dmenu_run` as it starts up immediately.
# It takes a bit of time to setup PROGRAMS tho.

PROGRAMS=( "alacritty"
	   "emacs"
	   "chromium-browser-privacy"
	   "gimp"
	   "telegram-desktop"
	   "torbrowser-launcher"
	   "transmission-qt"
	   "xreader"
	 )

printf "%s\n" "${PROGRAMS[@]}" | dmenu -p "Launch:" | sh -e
