#!/bin/sh
#
# A dmenu script to search the web around.


WEBSITES=( "duckduckgo"
	   "nyaa"
	   "invidious"
	   "youtube")

x=$(printf "%s\n" "${WEBSITES[@]}" | dmenu -i -p "Web launcher:")

case "$x" in
    "duckduckgo")
	y=$(dmenu -p "DuckDuckGo:")
	z=$(printf "https://duckduckgo.com/?q=%s" "$y")
	xdg-open "$z"
	;;
    "nyaa")
	y=$(dmenu -p "Nyaa:")
	z=$(printf "https://nyaa.si/?f=0&c=0_0&q=%s" "$y")
	xdg-open "$z"
	;;
    "invidious")
	y=$(dmenu -p "Invidious:")
	z=$(printf "https://invidio.us/search?q=%s" "$y")
	xdg-open "$z"
	;;
    "youtube")
	y=$(dmenu -p "Youtuebe:")
	z=$(printf "https://www.youtube.com/results?search_query=%s" "$y")
	xdg-open "$z"
	;;
esac
