#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT1/capacity) || exit
status=$(cat /sys/class/power_supply/BAT1/status) || exit

if [ "$capacity" -ge 75 ]; then
	capacity_color="#A6E22E"
elif [ "$capacity" -ge 50 ]; then
	capacity_color="#F8F8F2"
elif [ "$capacity" -ge 25 ]; then
	capacity_color="#FD971F"
else
	capacity_color="#FF6666"
fi

if [ "$status" = "Charging" ]; then
    status_color="#A6E22E"
    status="(Charging) "
elif [ "$status" = "Full" ]; then
    status_color="#F8F8F2"
    status=""
else
    status_color="#FD971F"
    status="(Discharging) "
fi

printf "BAT: "
printf "<fc=%s>%s</fc>" "$status_color" "$status" 
printf "<fc=%s>%s</fc>%%\n" "$capacity_color" "$capacity"
