#!/bin/sh

capacity=$(cat /sys/class/power_supply/BAT1/capacity) || exit
status=$(cat /sys/class/power_supply/BAT1/status) || exit

if [ "$capacity" -ge 75 ]; then
	capacity_color="#00AA00"
elif [ "$capacity" -ge 50 ]; then
	capacity_color="#ffffff"
elif [ "$capacity" -ge 25 ]; then
	capacity_color="#AA5500"
else
	capacity_color="#AA0000"
fi

if [ "$status" = "Charging" ]; then
    status_color="#00AA00"
    status="(Charging) "
elif [ "$status" = "Full" ]; then
    status_color="#ffffff"
    status=""
else
    status_color="#AA5500"
    status="(Discharging) "
fi

printf "BAT: "
printf "<span color='%s'>%s</span>" "$status_color" "$status" 
printf "<span color='%s'>%s</span>%%\n" "$capacity_color" "$capacity"
