#!/bin/sh

[ "$(stat -c %y ~/.cache/corona 2> /dev/null | cut -d' ' -f1)" != "$(date '+%Y-%m-%d')" ] &&
    curl -s https://corona-stats.online/Italy > $HOME/.cache/corona

grep "Italy" $HOME/.cache/corona |
    sed 's/\x1B\[[0-9;]*[a-zA-Z]//g; s/\s*//g; s/║//g; s/│/;/g' |
    awk -F';' '{print "CORONA: " $3 " infected (" $9 "); " $5 " dead (" $7 " %)"}'
