#! /bin/sh

xsetroot -gray
setxkbmap -option ctrl:nocaps -option compose:menu

sxhkd &
transmission-daemon &

bspc monitor -d 1

# Basic settings.
bspc config border_width 2
bspc config honor_size_hints true

bspc config focused_border_color "#005577"
bspc config active_border_color  "#222222"
bspc config normal_border_color  "#222222"

# Float all the windows.
bspc rule -a "*"   state=floating
bspc rule -a "mpv" rectangle=890x500+0+0 center=on
